const express=require("express");const path=require("path");const fs=require("fs");const bcrypt=require("bcryptjs");const jwt=require("jsonwebtoken");
const app=express(),PORT=process.env.PORT||3000,JWT_SECRET=process.env.JWT_SECRET||"RUTAAERO_DEV_CAMBIAR_EN_PRODUCCION",DB=path.join(__dirname,"data.json");
function load(){if(!fs.existsSync(DB))fs.writeFileSync(DB,JSON.stringify({users:[],vehicles:[],routes:[],pickupPoints:[],bookings:[],tokenTransactions:[]},null,2));return JSON.parse(fs.readFileSync(DB,"utf8"))}function save(db){fs.writeFileSync(DB,JSON.stringify(db,null,2))}function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function auth(req,res,next){const h=req.headers.authorization||"";if(!h.startsWith("Bearer "))return res.status(401).json({error:"No autenticado"});try{req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch{return res.status(401).json({error:"Token no válido"})}}
function safeUser(u){return{id:u.id,name:u.name,email:u.email,role:u.role,tokens:u.tokens}}
function num(v){return Number.isFinite(Number(v))?Number(v):null}
function distanceKm(aLat,aLng,bLat,bLng){const R=6371,rad=Math.PI/180,dLat=(bLat-aLat)*rad,dLng=(bLng-aLng)*rad,s=Math.sin(dLat/2)**2+Math.cos(aLat*rad)*Math.cos(bLat*rad)*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(s),Math.sqrt(1-s))}
function estimateMinutes(a,b){if(!a||!b||a.lat==null||a.lng==null||b.lat==null||b.lng==null)return null;const roadFactor=1.25,avgKmh=45;return Math.max(2,Math.round(distanceKm(a.lat,a.lng,b.lat,b.lng)*roadFactor/avgKmh*60))}
function routeWithEtas(r,db,includePrivate){const points=db.pickupPoints.filter(p=>p.routeId===r.id).sort((a,b)=>a.stopOrder-b.stopOrder);let prev=r.privateStartLat!=null?{lat:r.privateStartLat,lng:r.privateStartLng}:null;let t=new Date(r.departureTime);const out=points.map(p=>{let cur={lat:num(p.latitude),lng:num(p.longitude)},mins=estimateMinutes(prev,cur);if(mins!=null)t=new Date(t.getTime()+mins*60000);const x={...p};if(mins!=null)x.estimatedArrival=t.toISOString();prev=cur;return x});const base={...r,pickupPoints:out};if(!includePrivate){delete base.privateStartLat;delete base.privateStartLng}return base}
app.use(express.json());app.use(express.static(path.join(__dirname,"public")));
app.post("/api/auth/register",(req,res)=>{const{name,email,password,role}=req.body;if(!name||!email||!password||!["conductor","pasajero"].includes(role))return res.status(400).json({error:"Datos incompletos"});if(password.length<6)return res.status(400).json({error:"La contraseña debe tener 6 caracteres o más"});const db=load(),e=email.toLowerCase().trim();if(db.users.some(u=>u.email===e))return res.status(409).json({error:"El email ya está registrado"});const u={id:id(),name:name.trim(),email:e,passwordHash:bcrypt.hashSync(password,10),role,tokens:10,createdAt:new Date().toISOString()};db.users.push(u);db.tokenTransactions.push({id:id(),userId:u.id,amount:10,reason:"Bono inicial",createdAt:new Date().toISOString()});save(db);const token=jwt.sign({id:u.id,role:u.role},JWT_SECRET,{expiresIn:"7d"});res.status(201).json({token,user:safeUser(u)})});
app.post("/api/auth/login",(req,res)=>{const db=load(),e=String(req.body.email||"").toLowerCase().trim(),u=db.users.find(x=>x.email===e);if(!u||!bcrypt.compareSync(req.body.password||"",u.passwordHash))return res.status(401).json({error:"Email o contraseña incorrectos"});res.json({token:jwt.sign({id:u.id,role:u.role},JWT_SECRET,{expiresIn:"7d"}),user:safeUser(u)})});
app.get("/api/me",auth,(req,res)=>{const u=load().users.find(x=>x.id===req.user.id);if(!u)return res.status(404).json({error:"Usuario no encontrado"});res.json(safeUser(u))});
app.put("/api/me",auth,(req,res)=>{const db=load(),u=db.users.find(x=>x.id===req.user.id);if(req.body.name)u.name=String(req.body.name).trim();if(["conductor","pasajero"].includes(req.body.role))u.role=req.body.role;save(db);res.json(safeUser(u))});
app.get("/api/vehicles",auth,(req,res)=>res.json(load().vehicles.filter(v=>v.userId===req.user.id)));
app.post("/api/vehicles",auth,(req,res)=>{if(req.user.role!=="conductor")return res.status(403).json({error:"Solo un conductor puede registrar vehículos"});const{brand,model,plate,seats}=req.body,n=Number(seats);if(!brand||!model||!plate||!Number.isInteger(n)||n<1||n>9)return res.status(400).json({error:"Datos del vehículo no válidos"});const db=load(),p=String(plate).toUpperCase().trim();if(db.vehicles.some(v=>v.plate===p))return res.status(409).json({error:"La matrícula ya existe"});const v={id:id(),userId:req.user.id,brand,model,plate:p,seats:n};db.vehicles.push(v);save(db);res.status(201).json(v)});
app.delete("/api/vehicles/:id",auth,(req,res)=>{const db=load(),vehicle=db.vehicles.find(v=>v.id===req.params.id&&v.userId===req.user.id);if(!vehicle)return res.status(404).json({error:"Vehículo no encontrado"});if(db.routes.some(r=>r.vehicleId===vehicle.id))return res.status(400).json({error:"No puedes eliminar un vehículo que ya tiene rutas. Elimina o finaliza primero esas rutas."});db.vehicles=db.vehicles.filter(v=>v.id!==vehicle.id);save(db);res.json({ok:true})});
app.post("/api/routes",auth,(req,res)=>{if(req.user.role!=="conductor")return res.status(403).json({error:"Solo un conductor puede crear rutas"});const db=load(),vehicleId=String(req.body.vehicleId||"").trim(),origin=String(req.body.origin||"").trim(),destination=String(req.body.destination||"").trim(),departureTime=String(req.body.departureTime||"").trim(),n=parseInt(req.body.availableSeats,10),v=db.vehicles.find(x=>String(x.id)===vehicleId&&x.userId===req.user.id),privateStartLat=num(req.body.privateStartLat),privateStartLng=num(req.body.privateStartLng);if(!v)return res.status(400).json({error:"El vehículo seleccionado no existe."});if(!origin||!destination||!departureTime)return res.status(400).json({error:"Faltan datos de la ruta."});if(!Number.isFinite(n)||n<1||n>Number(v.seats))return res.status(400).json({error:"Plazas disponibles no válidas."});const r={id:id(),driverId:req.user.id,vehicleId:v.id,origin,destination,departureTime,availableSeats:n,status:"active",privateStartLat,privateStartLng};db.routes.push(r);save(db);res.status(201).json(r)});
app.get("/api/routes",(req,res)=>{const db=load();const out=db.routes.filter(r=>r.status==="active"&&r.availableSeats>0).map(r=>{const d=db.users.find(u=>u.id===r.driverId),v=db.vehicles.find(x=>x.id===r.vehicleId),x=routeWithEtas(r,db,false);return{...x,driverName:d?.name||"Desconocido",brand:v?.brand||"",model:v?.model||"",vehicleSeats:v?.seats||0}});res.json(out)});
app.delete("/api/routes/:id",auth,(req,res)=>{const db=load(),r=db.routes.find(x=>x.id===req.params.id&&x.driverId===req.user.id);if(!r)return res.status(404).json({error:"Ruta no encontrada"});if(db.bookings.some(b=>b.routeId===r.id))return res.status(400).json({error:"Esta ruta tiene reservas. No se puede eliminar; primero debes gestionar las reservas."});db.pickupPoints=db.pickupPoints.filter(p=>p.routeId!==r.id);db.routes=db.routes.filter(x=>x.id!==r.id);save(db);res.json({ok:true})});
app.post("/api/routes/:id/pickup-points",auth,(req,res)=>{const db=load(),r=db.routes.find(x=>x.id===req.params.id&&x.driverId===req.user.id);if(!r)return res.status(404).json({error:"Ruta no encontrada"});const p={id:id(),routeId:r.id,name:String(req.body.name||`Punto ${(db.pickupPoints.filter(x=>x.routeId===r.id).length+1)}`),latitude:num(req.body.latitude),longitude:num(req.body.longitude),stopOrder:Number(req.body.stopOrder)||1};db.pickupPoints.push(p);save(db);res.status(201).json(p)});
app.get("/api/routes/:id/pickup-points",(req,res)=>{const db=load(),r=db.routes.find(x=>x.id===req.params.id);if(!r)return res.status(404).json({error:"Ruta no encontrada"});res.json(routeWithEtas(r,db,false).pickupPoints)});
app.delete("/api/routes/:routeId/pickup-points/:pointId",auth,(req,res)=>{const db=load(),r=db.routes.find(x=>x.id===req.params.routeId&&x.driverId===req.user.id);if(!r)return res.status(404).json({error:"Ruta no encontrada"});const i=db.pickupPoints.findIndex(p=>p.id===req.params.pointId&&p.routeId===r.id);if(i<0)return res.status(404).json({error:"Punto de recogida no encontrado"});db.pickupPoints.splice(i,1);db.pickupPoints.filter(p=>p.routeId===r.id).sort((a,b)=>a.stopOrder-b.stopOrder).forEach((p,j)=>p.stopOrder=j+1);save(db);res.json({ok:true})});
app.get("/api/my-routes",auth,(req,res)=>{const db=load();res.json(db.routes.filter(r=>r.driverId===req.user.id).map(r=>{const v=db.vehicles.find(x=>x.id===r.vehicleId),x=routeWithEtas(r,db,true),bookings=db.bookings.filter(b=>b.routeId===r.id).map(b=>{const passenger=db.users.find(u=>u.id===b.passengerId),point=x.pickupPoints.find(p=>p.id===b.pickupPointId);return{id:b.id,status:b.status,passengerName:passenger?.name||"Usuario",passengerEmail:passenger?.email||"",pickupPoint:point?.name||"Punto",estimatedArrival:point?.estimatedArrival||null,createdAt:b.createdAt}});return{...x,vehicle:v||null,bookings}}))});
app.post("/api/bookings",auth,(req,res)=>{if(req.user.role!=="pasajero")return res.status(403).json({error:"Solo un pasajero puede reservar"});const db=load(),r=db.routes.find(x=>x.id===req.body.routeId&&x.status==="active");if(!r||r.availableSeats<1)return res.status(400).json({error:"No hay plazas disponibles"});const p=db.pickupPoints.find(x=>x.id===req.body.pickupPointId&&x.routeId===r.id),u=db.users.find(x=>x.id===req.user.id);if(!p)return res.status(400).json({error:"Punto de recogida no válido"});if(u.tokens<1)return res.status(400).json({error:"No tienes tokens suficientes"});u.tokens--;r.availableSeats--;db.bookings.push({id:id(),routeId:r.id,passengerId:u.id,pickupPointId:p.id,status:"pending",createdAt:new Date().toISOString()});db.tokenTransactions.push({id:id(),userId:u.id,amount:-1,reason:"Reserva de viaje",createdAt:new Date().toISOString()});save(db);res.status(201).json({ok:true})});
app.get("/api/my-bookings",auth,(req,res)=>{const db=load();res.json(db.bookings.filter(b=>b.passengerId===req.user.id).map(b=>{const r=db.routes.find(x=>x.id===b.routeId),d=r?db.users.find(u=>u.id===r.driverId):null,p=db.pickupPoints.find(x=>x.id===b.pickupPointId),rp=r?routeWithEtas(r,db,false):null,ep=rp?.pickupPoints.find(x=>x.id===b.pickupPointId);return{...b,route:r||null,driverName:d?.name||"Desconocido",pickupPoint:p?.name||"Punto",estimatedArrival:ep?.estimatedArrival||null}}))});
app.patch("/api/bookings/:id",auth,(req,res)=>{const db=load(),b=db.bookings.find(x=>x.id===req.params.id);if(!b)return res.status(404).json({error:"Reserva no encontrada"});const r=db.routes.find(x=>x.id===b.routeId);if(!r||r.driverId!==req.user.id)return res.status(403).json({error:"No tienes permiso"});if(!["accepted","rejected"].includes(req.body.status)||b.status!=="pending")return res.status(400).json({error:"Estado no válido"});if(req.body.status==="rejected"){const u=db.users.find(x=>x.id===b.passengerId);if(u){u.tokens+=1;db.tokenTransactions.push({id:id(),userId:u.id,amount:1,reason:"Devolución por reserva rechazada",createdAt:new Date().toISOString()});r.availableSeats+=1}}b.status=req.body.status;save(db);res.json(b)});
app.post("/api/tokens/reward",auth,(req,res)=>{const db=load(),u=db.users.find(x=>x.id===req.user.id);u.tokens+=5;db.tokenTransactions.push({id:id(),userId:u.id,amount:5,reason:"Recompensa de vídeo",createdAt:new Date().toISOString()});save(db);res.json({id:u.id,tokens:u.tokens})});
app.get("/api/health",(req,res)=>res.json({ok:true,service:"RutaAero API",version:"0.3.0"}));app.use((req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));app.listen(PORT,()=>console.log(`RutaAero funcionando en http://localhost:${PORT}`));
